# Generated by Django 3.2.9 on 2022-10-22 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0002_auto_20221022_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Actualizacion',
        ),
    ]
