# Generated by Django 3.2.9 on 2022-10-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0003_rename_projects_actualizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualizacion',
            options={'ordering': ['-created'], 'verbose_name': 'actualización', 'verbose_name_plural': 'actualizaciones'},
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección web'),
        ),
    ]
