# Generated by Django 3.2.9 on 2023-04-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0004_auto_20221022_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualizacion',
            name='description',
        ),
    ]
