# Generated by Django 3.2.9 on 2023-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0005_remove_actualizacion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='hola',
            field=models.CharField(default=555, max_length=100, verbose_name='Hola'),
            preserve_default=False,
        ),
    ]
