# Generated by Django 3.2.9 on 2023-04-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0006_actualizacion_hola'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actualizacion',
            new_name='Actualizacion1',
        ),
    ]
